### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by timdittmann**
addressing [Issue 247](https://github.com/kristinemlarson/gnssrefl/issues/247): notes and context described in the issue.

### CODE REVIEW

**Comment by timdittmann** [comment]
This fails the [smoke test for listing the pickle file](https://github.com/kristinemlarson/gnssrefl/blob/ab208adabb65082263c0b3c2c799ca47c04a5b33/software_tests#L17) now that we have deleted the copy command from the Dockerfile.
We could remove this check or add some logic to check the repo path for the pickle file?

**Comment by timdittmann** [comment]
I commented out the pickle file check in the smoke test, but alternatively we could switch to: ls -l gnssrefl/gpt_1wA.pickle or copy the file into the $REFL_CODE in the smoke test run and then check if you wish to keep this test?

**Comment by kristinemlarson** [comment]
i'm not going to be able to respond to this until after the class.  no point having a ls command that returns an error like that.  we can simply retain the cp commands in Dockerfile and provide better documentation for why it is there.

**Comment by kristinemlarson** [comment]
I'll go ahead and change the documentation so that it explains why it is making those directories. Thanks much for looking into this.

**Pull request closed without merging**
